name: build

on:
  push:
    branches:
      - main
      - production
    # except for those only changing documentation or terraform to save minutes
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'deploy/**'
  # Run the build for all pull requests
  # pull_request:
  #   # except for those only changing documentation or terraform to save minutes
  #   paths-ignore:
  #     - 'docs/**'
  #     - '**.md'
  #     - 'deploy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/AllenInstitute/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.MODULE_TOKEN }}

      - name: Restore Dependencies from Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore -warnaserror

      - name: Test
        run: |
          dotnet test --no-restore --logger "console;verbosity=normal"
